/*
 * SudokuSolverWindow.java
 *
 * Author: Jacob Boertjes
 *
 * Purpose: Provides a GUI for user to input a sudoku problem
 *
 * Revisions:
 *  File Created - Jan 3, 2018
 */
package sudokusolver;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author jacob
 *
 * Info:
 *      All text boxes are named with format: "textBox<row><col>"\
 *          Example: top left box is textBox00, next one in row is textBox01 etc
 */
public class SudokuSolverWindow extends javax.swing.JFrame {

    /* An array to access all textFields */

    // An array to keep all textFields in order
    public JTextField textFields[][];

    // Allow public access to button
    JButton solveButton;

    /**
     * Creates new form SudokuSolverWindow
     */
    public SudokuSolverWindow() {
        initComponents();

        // Initialize all the text fields into array
        textFields = new JTextField[][]{
            {textBox00, textBox01, textBox02, textBox03, textBox04, textBox05, textBox06, textBox07, textBox08},
            {textBox10, textBox11, textBox12, textBox13, textBox14, textBox15, textBox16, textBox17, textBox18},
            {textBox20, textBox21, textBox22, textBox23, textBox24, textBox25, textBox26, textBox27, textBox28},
            {textBox30, textBox31, textBox32, textBox33, textBox34, textBox35, textBox36, textBox37, textBox38},
            {textBox40, textBox41, textBox42, textBox43, textBox44, textBox45, textBox46, textBox47, textBox48},
            {textBox50, textBox51, textBox52, textBox53, textBox54, textBox55, textBox56, textBox57, textBox58},
            {textBox60, textBox61, textBox62, textBox63, textBox64, textBox65, textBox66, textBox67, textBox68},
            {textBox70, textBox71, textBox72, textBox73, textBox74, textBox75, textBox76, textBox77, textBox78},
            {textBox80, textBox81, textBox82, textBox83, textBox84, textBox85, textBox86, textBox87, textBox88}
        };

        // Initialize the Solve Button
        solveButton = solveBtn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topLeftPanel = new javax.swing.JPanel();
        textBox00 = new javax.swing.JTextField();
        textBox01 = new javax.swing.JTextField();
        textBox02 = new javax.swing.JTextField();
        textBox10 = new javax.swing.JTextField();
        textBox11 = new javax.swing.JTextField();
        textBox12 = new javax.swing.JTextField();
        textBox20 = new javax.swing.JTextField();
        textBox21 = new javax.swing.JTextField();
        textBox22 = new javax.swing.JTextField();
        topMidPanel = new javax.swing.JPanel();
        textBox03 = new javax.swing.JTextField();
        textBox04 = new javax.swing.JTextField();
        textBox05 = new javax.swing.JTextField();
        textBox13 = new javax.swing.JTextField();
        textBox14 = new javax.swing.JTextField();
        textBox15 = new javax.swing.JTextField();
        textBox23 = new javax.swing.JTextField();
        textBox25 = new javax.swing.JTextField();
        textBox24 = new javax.swing.JTextField();
        topRightPanel = new javax.swing.JPanel();
        textBox06 = new javax.swing.JTextField();
        textBox07 = new javax.swing.JTextField();
        textBox08 = new javax.swing.JTextField();
        textBox16 = new javax.swing.JTextField();
        textBox17 = new javax.swing.JTextField();
        textBox18 = new javax.swing.JTextField();
        textBox26 = new javax.swing.JTextField();
        textBox27 = new javax.swing.JTextField();
        textBox28 = new javax.swing.JTextField();
        midLeftPanel = new javax.swing.JPanel();
        textBox30 = new javax.swing.JTextField();
        textBox31 = new javax.swing.JTextField();
        textBox32 = new javax.swing.JTextField();
        textBox40 = new javax.swing.JTextField();
        textBox41 = new javax.swing.JTextField();
        textBox42 = new javax.swing.JTextField();
        textBox50 = new javax.swing.JTextField();
        textBox51 = new javax.swing.JTextField();
        textBox52 = new javax.swing.JTextField();
        midMidPanel = new javax.swing.JPanel();
        textBox33 = new javax.swing.JTextField();
        textBox34 = new javax.swing.JTextField();
        textBox35 = new javax.swing.JTextField();
        textBox43 = new javax.swing.JTextField();
        textBox44 = new javax.swing.JTextField();
        textBox45 = new javax.swing.JTextField();
        textBox53 = new javax.swing.JTextField();
        textBox54 = new javax.swing.JTextField();
        textBox55 = new javax.swing.JTextField();
        midRightPanel = new javax.swing.JPanel();
        textBox36 = new javax.swing.JTextField();
        textBox37 = new javax.swing.JTextField();
        textBox38 = new javax.swing.JTextField();
        textBox46 = new javax.swing.JTextField();
        textBox47 = new javax.swing.JTextField();
        textBox48 = new javax.swing.JTextField();
        textBox56 = new javax.swing.JTextField();
        textBox57 = new javax.swing.JTextField();
        textBox58 = new javax.swing.JTextField();
        botLeftPanel = new javax.swing.JPanel();
        textBox60 = new javax.swing.JTextField();
        textBox61 = new javax.swing.JTextField();
        textBox62 = new javax.swing.JTextField();
        textBox70 = new javax.swing.JTextField();
        textBox71 = new javax.swing.JTextField();
        textBox72 = new javax.swing.JTextField();
        textBox80 = new javax.swing.JTextField();
        textBox81 = new javax.swing.JTextField();
        textBox82 = new javax.swing.JTextField();
        midMidPanel1 = new javax.swing.JPanel();
        textBox63 = new javax.swing.JTextField();
        textBox64 = new javax.swing.JTextField();
        textBox65 = new javax.swing.JTextField();
        textBox73 = new javax.swing.JTextField();
        textBox74 = new javax.swing.JTextField();
        textBox75 = new javax.swing.JTextField();
        textBox83 = new javax.swing.JTextField();
        textBox84 = new javax.swing.JTextField();
        textBox85 = new javax.swing.JTextField();
        midRightPanel1 = new javax.swing.JPanel();
        textBox66 = new javax.swing.JTextField();
        textBox67 = new javax.swing.JTextField();
        textBox68 = new javax.swing.JTextField();
        textBox76 = new javax.swing.JTextField();
        textBox77 = new javax.swing.JTextField();
        textBox78 = new javax.swing.JTextField();
        textBox86 = new javax.swing.JTextField();
        textBox87 = new javax.swing.JTextField();
        textBox88 = new javax.swing.JTextField();
        solveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sudoku Solver");
        setAlwaysOnTop(true);

        topLeftPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        topLeftPanel.setMaximumSize(new java.awt.Dimension(150, 150));
        topLeftPanel.setMinimumSize(new java.awt.Dimension(150, 150));

        textBox00.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox00.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox00.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox01.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox01.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox02.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox02.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox10.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox11.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox12.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox20.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox21.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox22.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout topLeftPanelLayout = new javax.swing.GroupLayout(topLeftPanel);
        topLeftPanel.setLayout(topLeftPanelLayout);
        topLeftPanelLayout.setHorizontalGroup(
            topLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topLeftPanelLayout.createSequentialGroup()
                        .addComponent(textBox00, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox01, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox02, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(topLeftPanelLayout.createSequentialGroup()
                        .addComponent(textBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(topLeftPanelLayout.createSequentialGroup()
                        .addComponent(textBox20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topLeftPanelLayout.setVerticalGroup(
            topLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox00, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox01, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox02, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(topLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(topLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        topMidPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        topMidPanel.setMaximumSize(new java.awt.Dimension(150, 150));
        topMidPanel.setMinimumSize(new java.awt.Dimension(150, 150));

        textBox03.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox03.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox03.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox04.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox04.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox04.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox05.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox05.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox05.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox13.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox14.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox15.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox23.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox25.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox24.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout topMidPanelLayout = new javax.swing.GroupLayout(topMidPanel);
        topMidPanel.setLayout(topMidPanelLayout);
        topMidPanelLayout.setHorizontalGroup(
            topMidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topMidPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topMidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topMidPanelLayout.createSequentialGroup()
                        .addComponent(textBox03, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox04, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox05, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(topMidPanelLayout.createSequentialGroup()
                        .addComponent(textBox13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(topMidPanelLayout.createSequentialGroup()
                        .addComponent(textBox23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topMidPanelLayout.setVerticalGroup(
            topMidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topMidPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topMidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox03, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox04, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox05, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(topMidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(topMidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        topRightPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        topRightPanel.setMaximumSize(new java.awt.Dimension(150, 150));
        topRightPanel.setMinimumSize(new java.awt.Dimension(150, 150));

        textBox06.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox06.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox06.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox07.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox07.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox07.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox08.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox08.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox08.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox16.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox17.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox18.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox26.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox27.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox28.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout topRightPanelLayout = new javax.swing.GroupLayout(topRightPanel);
        topRightPanel.setLayout(topRightPanelLayout);
        topRightPanelLayout.setHorizontalGroup(
            topRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topRightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topRightPanelLayout.createSequentialGroup()
                        .addComponent(textBox06, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox07, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox08, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(topRightPanelLayout.createSequentialGroup()
                        .addComponent(textBox16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(topRightPanelLayout.createSequentialGroup()
                        .addComponent(textBox26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topRightPanelLayout.setVerticalGroup(
            topRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topRightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox07, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox08, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox06, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(topRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(topRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        midLeftPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        midLeftPanel.setMaximumSize(new java.awt.Dimension(150, 150));
        midLeftPanel.setMinimumSize(new java.awt.Dimension(150, 150));

        textBox30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox30.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox31.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox32.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox40.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox40.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox41.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox41.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox42.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox42.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox50.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox50.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox51.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox51.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox52.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox52.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout midLeftPanelLayout = new javax.swing.GroupLayout(midLeftPanel);
        midLeftPanel.setLayout(midLeftPanelLayout);
        midLeftPanelLayout.setHorizontalGroup(
            midLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(midLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(midLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(midLeftPanelLayout.createSequentialGroup()
                        .addComponent(textBox30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textBox32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(midLeftPanelLayout.createSequentialGroup()
                        .addGroup(midLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(midLeftPanelLayout.createSequentialGroup()
                                .addComponent(textBox40, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textBox41, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textBox42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(midLeftPanelLayout.createSequentialGroup()
                                .addComponent(textBox50, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textBox51, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textBox52, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        midLeftPanelLayout.setVerticalGroup(
            midLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(midLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(midLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(midLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox40, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox41, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(midLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox50, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox51, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox52, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        midMidPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        midMidPanel.setMaximumSize(new java.awt.Dimension(150, 150));
        midMidPanel.setMinimumSize(new java.awt.Dimension(150, 150));

        textBox33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox33.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox34.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox35.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox43.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox43.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox44.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox44.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox45.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox45.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox53.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox53.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox53.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox54.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox54.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox54.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox55.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox55.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox55.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout midMidPanelLayout = new javax.swing.GroupLayout(midMidPanel);
        midMidPanel.setLayout(midMidPanelLayout);
        midMidPanelLayout.setHorizontalGroup(
            midMidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(midMidPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(midMidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(midMidPanelLayout.createSequentialGroup()
                        .addComponent(textBox33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox34, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox35, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(midMidPanelLayout.createSequentialGroup()
                        .addComponent(textBox43, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox44, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox45, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(midMidPanelLayout.createSequentialGroup()
                        .addComponent(textBox53, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox54, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        midMidPanelLayout.setVerticalGroup(
            midMidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(midMidPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(midMidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox34, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox35, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(midMidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox43, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox44, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox45, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(midMidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox53, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox54, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox55, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        midRightPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        midRightPanel.setMaximumSize(new java.awt.Dimension(150, 150));
        midRightPanel.setMinimumSize(new java.awt.Dimension(150, 150));

        textBox36.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox36.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox37.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox38.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox38.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox46.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox46.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox47.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox47.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox47.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox48.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox48.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox48.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox56.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox56.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox56.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox57.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox57.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox57.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox58.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox58.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox58.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout midRightPanelLayout = new javax.swing.GroupLayout(midRightPanel);
        midRightPanel.setLayout(midRightPanelLayout);
        midRightPanelLayout.setHorizontalGroup(
            midRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(midRightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(midRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(midRightPanelLayout.createSequentialGroup()
                        .addComponent(textBox36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox37, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox38, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(midRightPanelLayout.createSequentialGroup()
                        .addComponent(textBox46, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox48, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(midRightPanelLayout.createSequentialGroup()
                        .addComponent(textBox56, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox57, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox58, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        midRightPanelLayout.setVerticalGroup(
            midRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(midRightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(midRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox37, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox38, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(midRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox46, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox48, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(midRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox56, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox57, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox58, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        botLeftPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botLeftPanel.setMaximumSize(new java.awt.Dimension(150, 150));
        botLeftPanel.setMinimumSize(new java.awt.Dimension(150, 150));

        textBox60.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox60.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox60.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox61.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox61.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox61.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox62.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox62.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox62.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox70.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox70.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox70.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox71.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox71.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox71.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox72.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox72.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox72.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox80.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox80.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox80.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox81.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox81.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox81.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox82.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox82.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox82.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout botLeftPanelLayout = new javax.swing.GroupLayout(botLeftPanel);
        botLeftPanel.setLayout(botLeftPanelLayout);
        botLeftPanelLayout.setHorizontalGroup(
            botLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(botLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(botLeftPanelLayout.createSequentialGroup()
                        .addComponent(textBox60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox61, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox62, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(botLeftPanelLayout.createSequentialGroup()
                        .addComponent(textBox70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox72, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(botLeftPanelLayout.createSequentialGroup()
                        .addComponent(textBox80, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox81, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox82, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        botLeftPanelLayout.setVerticalGroup(
            botLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(botLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox61, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox62, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox60, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(botLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox72, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox70, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox71, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(botLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox80, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox81, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox82, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        midMidPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        midMidPanel1.setMaximumSize(new java.awt.Dimension(150, 150));
        midMidPanel1.setMinimumSize(new java.awt.Dimension(150, 150));

        textBox63.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox63.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox63.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox64.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox64.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox64.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox65.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox65.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox65.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox73.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox73.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox73.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox74.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox74.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox74.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox75.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox75.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox75.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox83.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox83.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox83.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox84.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox84.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox84.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox85.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox85.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox85.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout midMidPanel1Layout = new javax.swing.GroupLayout(midMidPanel1);
        midMidPanel1.setLayout(midMidPanel1Layout);
        midMidPanel1Layout.setHorizontalGroup(
            midMidPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(midMidPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(midMidPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(midMidPanel1Layout.createSequentialGroup()
                        .addComponent(textBox63, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox64, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox65, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(midMidPanel1Layout.createSequentialGroup()
                        .addComponent(textBox73, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox74, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox75, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(midMidPanel1Layout.createSequentialGroup()
                        .addComponent(textBox83, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox84, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        midMidPanel1Layout.setVerticalGroup(
            midMidPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(midMidPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(midMidPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox63, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox64, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox65, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(midMidPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox73, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox74, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox75, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(midMidPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox84, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox85, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox83, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        midRightPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        midRightPanel1.setMaximumSize(new java.awt.Dimension(150, 150));
        midRightPanel1.setMinimumSize(new java.awt.Dimension(150, 150));

        textBox66.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox66.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox66.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox67.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox67.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox67.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox68.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox68.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox68.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox76.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox76.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox76.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox77.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox77.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox77.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox78.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox78.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox78.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox86.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox86.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox86.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox87.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox87.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox87.setPreferredSize(new java.awt.Dimension(30, 30));

        textBox88.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBox88.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox88.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout midRightPanel1Layout = new javax.swing.GroupLayout(midRightPanel1);
        midRightPanel1.setLayout(midRightPanel1Layout);
        midRightPanel1Layout.setHorizontalGroup(
            midRightPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(midRightPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(midRightPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(midRightPanel1Layout.createSequentialGroup()
                        .addComponent(textBox66, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox67, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textBox68, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(midRightPanel1Layout.createSequentialGroup()
                        .addGroup(midRightPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(midRightPanel1Layout.createSequentialGroup()
                                .addComponent(textBox76, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textBox77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textBox78, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(midRightPanel1Layout.createSequentialGroup()
                                .addComponent(textBox86, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textBox87, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textBox88, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        midRightPanel1Layout.setVerticalGroup(
            midRightPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(midRightPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(midRightPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox67, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox66, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox68, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(midRightPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox78, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox76, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(midRightPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox86, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox87, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox88, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        solveBtn.setBackground(new java.awt.Color(102, 102, 102));
        solveBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        solveBtn.setForeground(new java.awt.Color(255, 255, 255));
        solveBtn.setText("Solve");
        solveBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(solveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botLeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(midLeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(topLeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(topMidPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(topRightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(midMidPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(midRightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(midMidPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(midRightPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(topRightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topMidPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topLeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(midRightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(midMidPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(midLeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(midRightPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(midMidPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botLeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(solveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SudokuSolverWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SudokuSolverWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SudokuSolverWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SudokuSolverWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SudokuSolverWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botLeftPanel;
    private javax.swing.JPanel midLeftPanel;
    private javax.swing.JPanel midMidPanel;
    private javax.swing.JPanel midMidPanel1;
    private javax.swing.JPanel midRightPanel;
    private javax.swing.JPanel midRightPanel1;
    private javax.swing.JButton solveBtn;
    private javax.swing.JTextField textBox00;
    private javax.swing.JTextField textBox01;
    private javax.swing.JTextField textBox02;
    private javax.swing.JTextField textBox03;
    private javax.swing.JTextField textBox04;
    private javax.swing.JTextField textBox05;
    private javax.swing.JTextField textBox06;
    private javax.swing.JTextField textBox07;
    private javax.swing.JTextField textBox08;
    private javax.swing.JTextField textBox10;
    private javax.swing.JTextField textBox11;
    private javax.swing.JTextField textBox12;
    private javax.swing.JTextField textBox13;
    private javax.swing.JTextField textBox14;
    private javax.swing.JTextField textBox15;
    private javax.swing.JTextField textBox16;
    private javax.swing.JTextField textBox17;
    private javax.swing.JTextField textBox18;
    private javax.swing.JTextField textBox20;
    private javax.swing.JTextField textBox21;
    private javax.swing.JTextField textBox22;
    private javax.swing.JTextField textBox23;
    private javax.swing.JTextField textBox24;
    private javax.swing.JTextField textBox25;
    private javax.swing.JTextField textBox26;
    private javax.swing.JTextField textBox27;
    private javax.swing.JTextField textBox28;
    private javax.swing.JTextField textBox30;
    private javax.swing.JTextField textBox31;
    private javax.swing.JTextField textBox32;
    private javax.swing.JTextField textBox33;
    private javax.swing.JTextField textBox34;
    private javax.swing.JTextField textBox35;
    private javax.swing.JTextField textBox36;
    private javax.swing.JTextField textBox37;
    private javax.swing.JTextField textBox38;
    private javax.swing.JTextField textBox40;
    private javax.swing.JTextField textBox41;
    private javax.swing.JTextField textBox42;
    private javax.swing.JTextField textBox43;
    private javax.swing.JTextField textBox44;
    private javax.swing.JTextField textBox45;
    private javax.swing.JTextField textBox46;
    private javax.swing.JTextField textBox47;
    private javax.swing.JTextField textBox48;
    private javax.swing.JTextField textBox50;
    private javax.swing.JTextField textBox51;
    private javax.swing.JTextField textBox52;
    private javax.swing.JTextField textBox53;
    private javax.swing.JTextField textBox54;
    private javax.swing.JTextField textBox55;
    private javax.swing.JTextField textBox56;
    private javax.swing.JTextField textBox57;
    private javax.swing.JTextField textBox58;
    private javax.swing.JTextField textBox60;
    private javax.swing.JTextField textBox61;
    private javax.swing.JTextField textBox62;
    private javax.swing.JTextField textBox63;
    private javax.swing.JTextField textBox64;
    private javax.swing.JTextField textBox65;
    private javax.swing.JTextField textBox66;
    private javax.swing.JTextField textBox67;
    private javax.swing.JTextField textBox68;
    private javax.swing.JTextField textBox70;
    private javax.swing.JTextField textBox71;
    private javax.swing.JTextField textBox72;
    private javax.swing.JTextField textBox73;
    private javax.swing.JTextField textBox74;
    private javax.swing.JTextField textBox75;
    private javax.swing.JTextField textBox76;
    private javax.swing.JTextField textBox77;
    private javax.swing.JTextField textBox78;
    private javax.swing.JTextField textBox80;
    private javax.swing.JTextField textBox81;
    private javax.swing.JTextField textBox82;
    private javax.swing.JTextField textBox83;
    private javax.swing.JTextField textBox84;
    private javax.swing.JTextField textBox85;
    private javax.swing.JTextField textBox86;
    private javax.swing.JTextField textBox87;
    private javax.swing.JTextField textBox88;
    private javax.swing.JPanel topLeftPanel;
    private javax.swing.JPanel topMidPanel;
    private javax.swing.JPanel topRightPanel;
    // End of variables declaration//GEN-END:variables
}
